import Head from "next/head";
import Portfolio from "../pages/portfolio";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineMail,
  AiOutlinePhone,
} from "react-icons/ai";
import { BsFillMoonFill, BsList } from "react-icons/bs"; //BsList
import { useEffect, useState } from "react";
import backend from "../public/backend.png";
import frontend from "../public/frontend.png";
import more from "../public/more.png";
import mainlogo from "../public/logo.png";
import Image from "next/image";
import { motion as m } from "framer-motion";
import Type from "./type";
import { shuffle } from "lodash"; // npm i lodash
// import $ from "jquery";
// import jawon from "../public/AIpicture.png";

// import { Link } from 'react-router-dom';

const textColor = [
  //"text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 to-yellow-600",
  "text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-teal-400",
  // "text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-orange-600",
];

const logoColor = [
  //"bg-gradient-to-r from-yellow-400 to-yellow-600 dark:text-black text-white",
  "bg-gradient-to-r from-sky-400 to-teal-400 dark:text-black text-white",
  //"bg-gradient-to-r from-orange-400 to-orange-600 dark:text-black text-white",
];

// $(function() {
//   $('#open').click(function() {
//     $('#list').toggle();
//   });
// })

export default function Home() {
  const [text, setText] = useState(null);

  useEffect(() => {
    setText(shuffle(textColor).pop());
  }); //changes when refreshed

  const [logo, setLogo] = useState(null);

  useEffect(() => {
    setLogo(shuffle(logoColor).pop());
  }); //changes when refreshed

  {
    /* Dark mode and Light mode */
  }
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div loading="lazy" className={darkMode ? "dark" : ""}>
      {/* Head Section */}
      <Head>
        <title>Jawon Winbush | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main section. The m before main is a framer motion component that shows a smooth transition when page displays. */}
      <m.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.75 }}
        className=" bg-white dark:bg-black uppercase font-AldotheApache"
        id="About"
      >
        <section className="min-h-screen">
          
          {/* <nav className="bg-white border-gray-200 px-2 sm:px-4 py-2.5   dark:bg-gray-900 flex-grow flex">
            <div  className="container flex flex-wrap items-center justify-between mx-auto">
              <a href="https://flowbite.com/"  className="flex items-center">
                <img
                  src="https://flowbite.com/docs/images/logo.svg"
                   className="h-6 mr-3 sm:h-9"
                  alt="Flowbite Logo"
                />
                <span  className="self-center text-xl font-semibold whitespace-nowrap dark:text-white">
                  Flowbite
                </span>
              </a>
              <button
                data-collapse-toggle="navbar-default"
                type="button"
                 className="inline-flex items-center p-2 ml-3 text-sm text-gray-500   md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                aria-controls="navbar-default"
                aria-expanded="false"
              >
                <BsList
                  id="list"
                  className=" cursor-pointer text-3xl md:hidden text-black dark:text-white"
                  aria-hidden="true"
                />
              </button>
              <div  className="hidden w-full md:block md:w-auto" id="navbar-open">
                <ul  className="flex flex-col p-4 mt-4 border border-gray-100   bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                  <li>
                    <a
                      href="#"
                       className="block py-2 pl-3 pr-4 text-white bg-blue-700   md:bg-transparent md:text-blue-700 md:p-0 dark:text-white"
                      aria-current="page"
                    >
                      Home
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                       className="block py-2 pl-3 pr-4 text-gray-700   hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                    >
                      About
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                       className="block py-2 pl-3 pr-4 text-gray-700   hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                    >
                      Services
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                       className="block py-2 pl-3 pr-4 text-gray-700   hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                    >
                      Pricing
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                       className="block py-2 pl-3 pr-4 text-gray-700   hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                    >
                      Contact
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </nav> */}
          <nav className=" shadow-xl py-2 mb-6 md:mb-12 flex justify-between bg-gradient-to-r from-black to-gray-800 px-10 fixed w-full z-50">
            <Image
              className={`text-3xl md:text-5xl px-4  -xl`}
              src={mainlogo}
              width={60}
              height={60}
            />

            <ul id="open"className="flex items-center md:px-10 px-4">
              <div className="navbar flex">
                <li className="about">
                  <a
                    className={`text-md md:text-2xl font-semibold px-4 py-2 border-none ml-8 ${text}`}
                    href="#About"
                  >
                    About
                  </a>
                </li>
                <li className="skills">
                  <a
                    className={`text-md md:text-2xl font-semibold px-4 py-2 border-none ml-8 ${text}`}
                    href="#Skills"
                  >
                    Skills
                  </a>
                </li>
                <li className="projects">
                  <a
                    className={`text-md md:text-2xl font-semibold px-4 py-2 border-none ml-8 ${text}`}
                    href="#Projects"
                  >
                    Projects
                  </a>
                </li>

                <li className="contact">
                  <a
                    className={`text-md md:text-2xl font-semibold px-4 py-2 border-none ml-8 ${text}`}
                    href="#Contact"
                  >
                    Contact
                  </a>
                </li>
              </div>

              <li>
                <BsFillMoonFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="text-lg md:text-2xl  text-white dark:text-yellow-500 md:ml-8 mx-4 cursor-pointer"
                />
              </li>

              {/* <li>
                <BsList className="cursor-pointer text-3xl md:hidden text-white" id="list"/>
              </li> */}
            </ul>
          </nav>
          <div className="text-center px-4 md:px-10 pt-36">
            <h2 className="text-5xl font-bold	md:text-8xl dark:text-white">
              Hello! My name is
              <span className={`${text}`}> JAWON WINBUSH</span>.
            </h2>
            <h3 className={`text-2xl py-2 ${text} md:text-5xl font-semibold`}>
              <Type />
            </h3>

            <div className="content md:justify-between justify-center flex pt-10">
              <p className=" text-gray-800 dark:text-gray-200 max-w-md md:max-w-4xl mx-auto text-lg whitespace-pre-line	md:text-4xl font-light mt-4 md:mt-10 ">
                A versatile software developer with 3+ years of experience in
                programming, UX design, and data management. A well-organized
                person, problem solver, and independent employee with high
                attention to detail. My objective is to develop websites and
                applications that make a difference. When I'm not coding I enjoy
                reading, watching soccer, and exercising. If you have a project
                in mind or would like to make an enquiry simply contact me
                below.
              </p>

              {/* <div className=" hero mx-auto bg-white-500  -2xl md:w-80 md:h-80 overflow-hidden mt-12 w-56 h-56 md:relative absolute items-center hover:shadow-xl">
                <Image
                  src={jawon}
                  layout="fill"
                  objectFit="cover"
                  className="object-top"
                />
              </div> */}
            </div>
          </div>
        </section>

        <section className="md:px-10 px-4">
          <div>
            <h3
              className={`text-3xl md:text-5xl font-semibold pt-20 text-center ${text}`}
              id="Skills"
            >
              Skills
            </h3>
            <p className="md:text-3xl text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 text-center pb-6">
              My professional skillset.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg dark:shadow-inner p-10  -xl my-10  dark:bg-white flex-1">
              <Image src={frontend} width={100} height={100} />
              <h3 className="text-2xl pt-8 pb-2 font-bold">Frontend</h3>

              <p className="text-gray-800 py-1 ">ReactJS</p>

              <p className="text-gray-800 py-1 ">JavaScript</p>

              <p className="text-gray-800 py-1 ">AngularJS</p>

              <p className="text-gray-800 py-1 ">jQuery</p>

              <p className="text-gray-800 py-1 ">HTML</p>

              <p className="text-gray-800 py-1 ">CSS</p>
            </div>
            <div className="text-center shadow-lg dark:shadow-inner p-10  -xl my-10 dark:bg-white flex-1">
              <Image
                priority
                src={backend}
                width={100}
                height={100}
                alt="Hero"
              />
              <h3 className="text-2xl pt-8 pb-2 font-bold">Backend</h3>

              <p className="text-gray-800 py-1 ">SQL & MySQL</p>

              <p className="text-gray-800 py-1 ">PHP & PhpMyAdmin</p>

              <p className="text-gray-800 py-1 ">NodeJS</p>

              <p className="text-gray-800 py-1 ">Python & Jupyter Notebook</p>

              <p className="text-gray-800 py-1 ">C#</p>

              <p className="text-gray-800 py-1 ">C++</p>

              <p className="text-gray-800 py-1 ">ASP.NET</p>

              <p className="text-gray-800 py-1 ">Java</p>
            </div>
            <div className="text-center shadow-lg p-10  -xl my-10 dark:bg-white flex-1">
              <Image src={more} width={100} height={100} />
              <h3 className="text-2xl pt-8 pb-2 font-bold">More</h3>
              <p className="text-gray-800 py-1 ">
                Visual Studio Code & Visual Studio
              </p>

              <p className="text-gray-800 py-1 ">Adobe Photoshop</p>

              <p className="text-gray-800 py-1 ">Adobe Illustrator</p>

              <p className="text-gray-800 py-1 ">PhpStorm</p>

              <p className="text-gray-800 py-1 ">WordPress</p>

              <p className="text-gray-800 py-1 ">Figma</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3
              className={`text-3xl md:text-5xl font-semibold pt-16 text-center ${text}`}
              id="Projects"
            >
              Projects
            </h3>
            <p className="md:text-3xl text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 text-center">
              My relevant projects.
            </p>
          </div>
          <Portfolio />
          {/* <!-- Container for demo purpose --> */}
{/* <div  className="container my-24 px-6 mx-auto">

  <section  className="mb-32 text-gray-800 text-center">

    <h2  className="text-3xl font-bold mb-12">Testimonials</h2>

    <div  className="grid md:grid-cols-3 gap-x-6 lg:gap-x-12">
      <div  className="mb-12 md:mb-0">
        <div  className="flex justify-center mb-6">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(1).jpg"  className=" -full shadow-lg w-32" />
        </div>
        <h5  className="text-lg font-bold mb-4">Maria Smantha</h5>
        <h6  className="font-medium text-blue-600 mb-4">Web Developer</h6>
        <p  className="mb-4">
          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="quote-left"
             className="w-6 pr-2 inline-block" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path fill="currentColor"
              d="M464 256h-80v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8c-88.4 0-160 71.6-160 160v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48zm-288 0H96v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8C71.6 32 0 103.6 0 192v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48z">
            </path>
          </svg>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod eos id officiis hic
          tenetur quae quaerat ad velit ab hic tenetur.
        </p>
        <ul  className="flex justify-center mb-0">
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star-half-alt"
               className="w-4 text-yellow-500" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 536 512">
              <path fill="currentColor"
                d="M508.55 171.51L362.18 150.2 296.77 17.81C290.89 5.98 279.42 0 267.95 0c-11.4 0-22.79 5.9-28.69 17.81l-65.43 132.38-146.38 21.29c-26.25 3.8-36.77 36.09-17.74 54.59l105.89 103-25.06 145.48C86.98 495.33 103.57 512 122.15 512c4.93 0 10-1.17 14.87-3.75l130.95-68.68 130.94 68.7c4.86 2.55 9.92 3.71 14.83 3.71 18.6 0 35.22-16.61 31.66-37.4l-25.03-145.49 105.91-102.98c19.04-18.5 8.52-50.8-17.73-54.6zm-121.74 123.2l-18.12 17.62 4.28 24.88 19.52 113.45-102.13-53.59-22.38-11.74.03-317.19 51.03 103.29 11.18 22.63 25.01 3.64 114.23 16.63-82.65 80.38z">
              </path>
            </svg>
          </li>
        </ul>
      </div>
      <div  className="mb-12 md:mb-0">
        <div  className="flex justify-center mb-6">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(2).jpg"  className=" -full shadow-lg w-32" />
        </div>
        <h5  className="text-lg font-bold mb-4">Lisa Cudrow</h5>
        <h6  className="font-medium text-blue-600 mb-4">Graphic Designer</h6>
        <p  className="mb-4">
          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="quote-left"
             className="w-6 pr-2 inline-block" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path fill="currentColor"
              d="M464 256h-80v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8c-88.4 0-160 71.6-160 160v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48zm-288 0H96v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8C71.6 32 0 103.6 0 192v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48z">
            </path>
          </svg>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit
          laboriosam, nisi ut aliquid commodi.
        </p>
        <ul  className="flex justify-center mb-0">
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
        </ul>
      </div>
      <div  className="mb-0">
        <div  className="flex justify-center mb-6">
          <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(9).jpg"  className=" -full shadow-lg w-32" />
        </div>
        <h5  className="text-lg font-bold mb-4">John Smith</h5>
        <h6  className="font-medium text-blue-600 mb-4">Marketing Specialist</h6>
        <p  className="mb-4">
          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="quote-left"
             className="w-6 pr-2 inline-block" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path fill="currentColor"
              d="M464 256h-80v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8c-88.4 0-160 71.6-160 160v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48zm-288 0H96v-64c0-35.3 28.7-64 64-64h8c13.3 0 24-10.7 24-24V56c0-13.3-10.7-24-24-24h-8C71.6 32 0 103.6 0 192v240c0 26.5 21.5 48 48 48h128c26.5 0 48-21.5 48-48V304c0-26.5-21.5-48-48-48z">
            </path>
          </svg>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium
          voluptatum deleniti atque corrupti.
        </p>
        <ul  className="flex justify-center mb-0">
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z">
              </path>
            </svg>
          </li>
          <li>
            <svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="star"  className="w-4 text-yellow-500"
              role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor"
                d="M528.1 171.5L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6zM388.6 312.3l23.7 138.4L288 385.4l-124.3 65.3 23.7-138.4-100.6-98 139-20.2 62.2-126 62.2 126 139 20.2-100.6 98z">
              </path>
            </svg>
          </li>
        </ul>
      </div>
    </div>

  </section>

</div> */}
{/* <!-- Container for demo purpose --> */}
          <div>
            <h3
              className={`text-3xl md:text-5xl font-semibold pt-24 text-center ${text}`}
              id="Contact"
            >
              Contact me
            </h3>
            <p className="md:text-3xl text-lg py-2 leading-8 text-gray-800 dark:text-gray-200 text-center pb-6">
              Let's talk.
            </p>
            <section>
              {/* <div className="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
                <form
                  action="mailto:jawonwinbush@gmail.com"
                  method="POST"
                  className="space-y-8"
                >
                  <div>
                    <label
                      for="email"
                      className="block mb-2 text-lg font-medium text-black dark:text-white"
                    >
                      Your email
                    </label>
                    <input
                      type="email"
                      id="email"
                      className="shadow-sm bg-gray-50 border border-gray-300 text-black text-lg   focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="name@example.com"
                      required
                    />
                  </div>
                  <div>
                    <label
                      for="subject"
                      className="block mb-2 text-lg font-medium text-black dark:text-white"
                    >
                      Subject
                    </label>
                    <input
                      type="text"
                      id="subject"
                      className="block p-3 w-full text-lg text-black dark:text-white bg-gray-50   border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400  dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                      placeholder="Your subject..."
                      required
                    />
                  </div>
                  <div  className="sm:col-span-2">
                    <label
                      for="message"
                      className="block mb-2 text-lg font-medium text-black dark:text-white"
                    >
                      Your message
                    </label>
                    <textarea
                      id="message"
                      rows="6"
                      className="block p-2.5 w-full text-lg text-gray-900 bg-gray-50   shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                      placeholder="Leave a comment..."
                    ></textarea>
                  </div>
                  <button
                    type="submit"
                    className="py-3 px-5 text-lg font-medium dark:text-white sm:w-fit focus:ring-4 focus:outline-none bg-gradient-to-r from-yellow-400 to-yellow-600   "
                  >
                    Send message
                  </button>
                </form>
              </div> */}
            </section>
          </div>
          <footer>
            <div className="text-5xl flex justify-center gap-10 md:gap-16 py-3 text-black dark:text-white">
              <a href="mailto:jawonwinbush@gmail.com" target={"_blank"}>
                <AiOutlineMail className="hover:cursor-pointer" />
              </a>
              <a href="tel:3176544324" target={"_blank"}>
                <AiOutlinePhone className="hover:cursor-pointer" />
              </a>
              <a
                href="https://www.linkedin.com/in/jawonmwinbush/"
                target={"_blank"}
              >
                <AiFillLinkedin className="hover:cursor-pointer" />
              </a>
              <a href="https://www.github.com/jwinbush/" target={"_blank"}>
                <AiFillGithub className="hover:cursor-pointer" />
              </a>
            </div>

            <div className=" pt-20 text-black dark:text-white md:text-md text-sm text-center">
              <p>Designed and developed with Next.js. Last updated - (2/27/2023)</p>
            </div>
          </footer>
        </section>
      </m.main>
    </div>
  );
}
